// Generated by CoffeeScript 1.8.0
(function() {
  var Mpeg1Muxer, child_process, events, util;

  child_process = require('child_process');

  util = require('util');

  events = require('events');

  Mpeg1Muxer = function(options) {
    var self;
    self = this;
    this.url = options.url;
    // var args = ["-rtsp_transport", "tcp", "-i", this.url, '-f', 'mpeg1video', '-b:v', '800k', '-r', '30', '-'];
    var args = ('-rtsp_transport tcp -i ' + this.url + ' -f mpeg1video -b:v 1000k -an -r 24 -').split(' ')
    console.log(args)
    this.stream = child_process.spawn("ffmpeg", args, {
      detached: false
    });
    this.inputStreamStarted = true;
    this.stream.stdout.on('data', function(data) {
      return self.emit('mpeg1data', data);
    });
    this.stream.stderr.on('data', function(data) {
      return self.emit('ffmpegError', data);
    });
    return this;
  };

  util.inherits(Mpeg1Muxer, events.EventEmitter);

  module.exports = Mpeg1Muxer;

}).call(this);
